import { Character } from './character';

export const CHARACTERS: Character[] = [
  { name: "Fox", tier: 0, stocks: 4, deceased: false, fileName: "fox.png" },
  { name: "Marth", tier: 1, stocks: 4, deceased: false, fileName: "marth.png" },
  { name: "Falco", tier: 2, stocks: 4, deceased: false, fileName: "falco.png" },
  { name: "Sheik", tier: 3, stocks: 4, deceased: false, fileName: "sheik.png" },
  { name: "Falcon", tier: 4, stocks: 4, deceased: false, fileName: "cfalcon.png" },
  { name: "Peach", tier: 5, stocks: 4, deceased: false, fileName: "peach.png" },
  { name: "Jigglypuff", tier: 6, stocks: 4, deceased: false, fileName: "jigglypuff.png" },
  { name: "Ice Climbers", tier: 7, stocks: 4, deceased: false, fileName: "iceclimbers.png" },
  { name: "Samus", tier: 8, stocks: 4, deceased: false, fileName: "samus.png" },
  { name: "Yoshi", tier: 9, stocks: 4, deceased: false, fileName: "yoshi.png" },
  { name: "Pikachu", tier: 10, stocks: 4, deceased: false, fileName: "pikachu.png" },
  { name: "Ganondorf", tier: 11, stocks: 4, deceased: false, fileName: "ganondorf.png" },
  { name: "Luigi", tier: 12, stocks: 4, deceased: false, fileName: "luigi.png" },
  { name: "Mario", tier: 13, stocks: 4, deceased: false, fileName: "mario.png" },
  { name: "Dr. Mario", tier: 14, stocks: 4, deceased: false, fileName: "drmario.png" },
  { name: "Donkey Kong", tier: 15, stocks: 4, deceased: false, fileName: "dk.png" },
  { name: "Mr. Game & Watch", tier: 16, stocks: 4, deceased: false, fileName: "mrgameandwatch.png" },
  { name: "Young Link", tier: 17, stocks: 4, deceased: false, fileName: "younglink.png" },
  { name: "Link", tier: 18, stocks: 4, deceased: false, fileName: "link.png" },
  { name: "Mewtwo", tier: 19, stocks: 4, deceased: false, fileName: "mewtwo.png" },
  { name: "Ness", tier: 20, stocks: 4, deceased: false, fileName: "ness.png" },
  { name: "Pichu", tier: 21, stocks: 4, deceased: false, fileName: "pichu.png" },
  { name: "Zelda", tier: 22, stocks: 4, deceased: false, fileName: "zelda.png" },
  { name: "Roy", tier: 23, stocks: 4, deceased: false, fileName: "roy.png" },
  { name: "Kirby", tier: 24, stocks: 4, deceased: false, fileName: "kirby.png" },
  { name: "Bowser", tier: 25, stocks: 4, deceased: false, fileName: "bowser.png" },
];